package com.dragonballzrpg.enums;

/**
 * Created by Carl on 11/04/2017.
 */
public enum AnimationName
{
    FACE_UP, FACE_DOWN, FACE_LEFT, FACE_RIGHT,
    WALK_UP, WALK_DOWN, WALK_LEFT, WALK_RIGHT,
    RUN_UP, RUN_DOWN, RUN_LEFT, RUN_RIGHT,
    PUNCH_UP_1, PUNCH_DOWN_1, PUNCH_LEFT_1, PUNCH_RIGHT_1,
    PUNCH_UP_2, PUNCH_DOWN_2, PUNCH_LEFT_2, PUNCH_RIGHT_2,
    KICK_UP, KICK_DOWN, KICK_LEFT, KICK_RIGHT,
    KI_BLAST_UP, KI_BLAST_DOWN, KI_BLAST_LEFT, KI_BLAST_RIGHT,
    CONTINUOUS_KI_BLAST_UP, CONTINUOUS_KI_BLAST_DOWN, CONTINUOUS_KI_BLAST_LEFT, CONTINUOUS_KI_BLAST_RIGHT,
    BEGIN_TRANSFORM_TO_SUPER, TRANSFORM_TO_SUPER, TRANSFORM_TO_BASE,
    KNOCKED_BACK_UP, KNOCKED_BACK_DOWN, KNOCKED_BACK_LEFT, KNOCKED_BACK_RIGHT,
    FLY_UP,
    DIE
}
