package com.dragonballzrpg.enums;

/**
 * Created by Carl on 08/06/2017.
 */
public enum MenuOption
{
    START, CONTROLS, EXIT,
    SET_UP_ACTION_INPUT, SET_DOWN_ACTION_INPUT, SET_LEFT_ACTION_INPUT, SET_RIGHT_ACTION_INPUT, SET_INTERACT_OR_MELEE_ACTION_INPUT,
    SET_CANCEL_OR_ENERGY_ATTACK_ACTION_INPUT, SET_SWITCH_ENERGY_ATTACK_ACTION_INPUT, SET_PAUSE_ACTION_INPUT,
    RESET_TO_DEFAULT, BACK,
    NULL
}
